---
- name: Deploy common components
  hosts: servers
  roles:
    - role: common
      tags: common
    - role: zabbix-agent
      tags: zabbix-agent
    - role: sys-agent
      tags: sys-agent
    - role: iperf3
      tags: iperf3
    - role: reproxy
      tags: reproxy
    - role: dufs
      tags: dufs
- name: Deploy helium-specific components
  hosts: helium
  roles:
    - role: cronn
      tags: cronn
    - role: postgresql
      tags: postgresql
    - role: grafana
      tags: grafana
    - role: zabbix-server
      tags: zabbix
    - role: zabbix-web
      tags: zabbix
    - role: powerdns
      tags: powerdns
    - role: mongodb
      tags: mongodb
    - role: ollama
      tags: ollama
    - role: adguard
      tags: adguard
    - role: home-assistant
      tags: home-assistant
    - role: transit-alert
      tags: transit-alert
- name: Deploy neon-specific components
  hosts: neon
  roles:
    - role: watchdog
      tags: watchdog
